env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    tsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
