env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    tsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/ban-types':
    - error
    - extendDefaults: false
      types:
        '{}': false
  '@typescript-eslint/no-explicit-any': off
